# Generated by Django 5.1.7 on 2025-03-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='task`s titele')),
                ('description', models.TextField(verbose_name='description of the task')),
                ('status', models.CharField(choices=[('in_prog', 'In Progress'), ('done', 'Done'), ('delayed', 'Delayed'), ('not_start', 'Not Started')], default='not_start', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('min', 'Medium Priority'), ('high', 'High Priority')], default='mid', max_length=5)),
                ('due_to', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
