# Generated by Django 5.1.7 on 2025-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_coment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='coment_pic',
            field=models.ImageField(blank=True, null=True, upload_to='coment_pics/'),
        ),
    ]
